Address review comments from @xiang90 and @aaronlevy.

diff --git a/hack/multi-node/bootkube-test-recovery b/hack/multi-node/bootkube-test-recovery
--- a/hack/multi-node/bootkube-test-recovery
+++ b/hack/multi-node/bootkube-test-recovery
@@ -5,13 +5,13 @@ GLOG_v=${GLOG_v:-1}
 HOST=${HOST:-c1}
 SELF_HOST_ETCD=${SELF_HOST_ETCD:-false}
 
-if [ ${SELF_HOST_ETCD} = "true" ]; then
-  echo "ERROR: bootkube-recover does not currently support self-hosted etcd."
-  exit 1
-fi
-
 if [ ! -d "cluster" ]; then
   echo "Need some cluster assets to perform recovery; try running bootkube-up."
+fi
+
+if [ -f cluster/bootstrap-manifests/bootstrap-etcd.yaml ]; then
+  echo "ERROR: $(basename $0) does not currently support self-hosted etcd."
+  exit 1
 fi
 
 echo
